

 # enabled: disabling this will halt all functionality of the plugin, applies after reload
enabled: true

 # kick_message: the message sent to players when crowbar is activated. {plugins} will be replaced with a list of
 #   plugins that are not loaded.
 # plugin_list_placeholder: The format of the {plugins} placeholder. Use {plugin} placeholder to target the individual plugin.
kick_message: '\n&c[Crowbar] &eThe server is currently whitelisted because the following plugins are not loaded:{plugins}'
plugin_list_placeholder: '\n&f -&7 {plugin}'

 # message sent to whitelisted players who join during crowbar event
crowbar_join_message: '&c[Crowbar] The server is currently whitelisted because the following plugins are not loaded: {plugins}'
crowbar_join_plugin_list_placeholder: '&e{plugin}&c, '

 # changes the server list motd and maxplayers when crowbar is engaged
server_list_motd:
  change_when_crowbar: true
  message: '&cError &8-&7 Required plugins not enabled.'
  maxplayers: 0

 # List the plugins that must be loaded for a non-whitelisted player joins.
required_plugins:
  - 'WorldGuard'